In [1]:
#Data Pre-procesing Step
# importing libraries
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [2]:
from google.colab import files
upload = files.upload() #uploading file

Saving suv_data.csv to suv_data.csv


In [3]:
upload

{'suv_data.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\n15624510,Male,19,19000,0\n15810944,Male,35,20000,0\n15668575,Female,26,43000,0\n15603246,Female,27,57000,0\n15804002,Male,19,76000,0\n15728773,Male,27,58000,0\n15598044,Female,27,84000,0\n15694829,Female,32,150000,1\n15600575,Male,25,33000,0\n15727311,Female,35,65000,0\n15570769,Female,26,80000,0\n15606274,Female,26,52000,0\n15746139,Male,20,86000,0\n15704987,Male,32,18000,0\n15628972,Male,18,82000,0\n15697686,Male,29,80000,0\n15733883,Male,47,25000,1\n15617482,Male,45,26000,1\n15704583,Male,46,28000,1\n15621083,Female,48,29000,1\n15649487,Male,45,22000,1\n15736760,Female,47,49000,1\n15714658,Male,48,41000,1\n15599081,Female,45,22000,1\n15705113,Male,46,23000,1\n15631159,Male,47,20000,1\n15792818,Male,49,28000,1\n15633531,Female,47,30000,1\n15744529,Male,29,43000,0\n15669656,Male,31,18000,0\n15581198,Male,31,74000,0\n15729054,Female,27,137000,1\n15573452,Female,21,16000,0\n15776733,Female,28,44000,0\n15724858,Male,27,9000

In [4]:
print(upload)

{'suv_data.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\n15624510,Male,19,19000,0\n15810944,Male,35,20000,0\n15668575,Female,26,43000,0\n15603246,Female,27,57000,0\n15804002,Male,19,76000,0\n15728773,Male,27,58000,0\n15598044,Female,27,84000,0\n15694829,Female,32,150000,1\n15600575,Male,25,33000,0\n15727311,Female,35,65000,0\n15570769,Female,26,80000,0\n15606274,Female,26,52000,0\n15746139,Male,20,86000,0\n15704987,Male,32,18000,0\n15628972,Male,18,82000,0\n15697686,Male,29,80000,0\n15733883,Male,47,25000,1\n15617482,Male,45,26000,1\n15704583,Male,46,28000,1\n15621083,Female,48,29000,1\n15649487,Male,45,22000,1\n15736760,Female,47,49000,1\n15714658,Male,48,41000,1\n15599081,Female,45,22000,1\n15705113,Male,46,23000,1\n15631159,Male,47,20000,1\n15792818,Male,49,28000,1\n15633531,Female,47,30000,1\n15744529,Male,29,43000,0\n15669656,Male,31,18000,0\n15581198,Male,31,74000,0\n15729054,Female,27,137000,1\n15573452,Female,21,16000,0\n15776733,Female,28,44000,0\n15724858,Male,27,9000

In [5]:
df = pd.read_csv('/content/suv_data.csv')  #reading dataset

In [6]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
#Extracting Independent and dependent Variable
x= df.iloc[:, [2,3]].values
y= df.iloc[:, 4].values

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
# Splitting the dataset into training and test set.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

#imports a function called train_test_split from the sklearn.model_selection module. This function is used to split datasets into two subsets:
# one for training a model and the other for testing its performance.

#x :independent and
# y: dependent variables
#25% of the data will be used for testing, while the remaining 75% will be used for training.
# random_state=0 : ensure that every time you run this code, the data is split in the same way

In [10]:
print(x_train.shape)

(300, 2)


In [11]:
print(x_test.shape)

(100, 2)


In [12]:
print(y_train.shape)

(300,)


In [13]:
print(y_test.shape)

(100,)


In [14]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler() # normalize or bring value in one range , creates an instance of the StandardScaler class. This object st_x will be used to scale your data.
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [15]:
#Creating a logistic regression model
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0) #creates an instance of the Logistic Regression classifier.
classifier.fit(x_train, y_train) #fit method is a fundamental function used to train a model on a dataset

LogisticRegression(random_state=0)

In [16]:
#Predicting the test set result
y_pred= classifier.predict(x_test)

In [17]:
y_pred # prediction done algo

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [18]:
#Creating the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
# ytest is test data target variable


In [19]:
cm

array([[65,  3],
       [ 8, 24]])